<?php
/**
 * Created by PhpStorm.
 * User:NyanTun
 * Date:4/30/2015
 * Time:11:45
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Proposals";
$this->headTitle($title);
$flashMesssages=$this->flashMessenger()->getMessages();
?>
<h1><?php echo $title;?></h1>
<?php if(count($flashMesssages) > 0) : ?>
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong><span class="glyphicon glyphicon-info-sign"></span></strong>
        <?php echo $flashMesssages[0]; ?>
    </div>
<?php endif;?>
<script type="text/javascript">
    $(document).ready(function(){
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url : '<?php echo $this->url('cr_proposal', array('action' => 'jsonDelete')) ?>',
                    data : $('input[name="chkId[]"]:checked'),
                    type : 'POST',
                    success : function(data){
                        if(data.message == "success"){
                            window.location.href = "<?php echo $this->url('cr_proposal'); ?>"
                        }else{
                            alert(data.message);
                        }
                    }
                });
            }
        });

        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });
        $('input[name="chkId[]"]').change(function(){
            var total = $('input[name="chkId[]"]').length;
            var checks = $('input[name="chkId[]"]:checked').length;
            if(total == checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('proposalFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("cr_proposal",array('action'=>'request','id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo$this->url('cr_proposal',array('action'=>'export')); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="50px">
                        <div class="checkbox" style="margin: 0">
                            <label class="checkbox-custom" data-initialize="checkbox">
                                <input type="checkbox" id="chkAll" />
                            </label>
                        </div>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Proposal code','code');?>
                    </th>
                    <th width="80px">
                        <?php echo $this->gridHeaderCell('Amount','amount');?>
                    </th>
                    <th class="120px">
                        <?php echo $this->gridHeaderCell('Proposal Date','proposalDate');?>
                    </th>
                    <th class="160px">
                        <?php echo $this->gridHeaderCell('Proposal Note','notes');?>
                    </th>
                    <th class="120px">
                        <?php echo $this->gridHeaderCell('Group Code','group_code');?>
                    </th>
                    <th class="120px">
                        <?php echo $this->gridHeaderCell('Status','status');?>
                    </th>
                    <th class="120px">
                        <?php echo $this->gridHeaderCell('File','proposalFile');?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $proposal) : ?>
                    <tr>
                        <td>
                            <div class="checkbox" style="margin: 0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($proposal->proposalId); ?>" />
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cr_proposal',array('action'=>'detail', 'id'=>$proposal->proposalId));?>" title="edit">
                                <?php echo $this->escapeHtml($proposal->code); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($proposal->amount);?>
                        </td>
                        <th>
                            <?php echo $this->escapeHtml($proposal->proposalDate);?>
                        </th>
                        <th>
                            <?php echo $this->escapeHtml($proposal->notes);?>
                        </th>
                        <th>
                            <?php echo $this->escapeHtml($proposal->group_code);?>
                        </th>
                        <th>
                            <?php
                            switch($proposal->status){
                                case 'A':
                                    echo 'Active';
                                    break;
                                case 'D':
                                    echo 'Inactive';
                                    break;
                                default:
                                    echo 'Invalid';
                                    break;
                            }
                            ?>
                        </th>
                        <th>
                            <?php echo $this->escapeHtml($proposal->proposalFile);?>
                        </th>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>

    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route'=>'cr_proposal', 'sort'=>$sort, 'sortBy'=>$sortBy));
            ?>
        </div>
    </div>
</div>



