<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 7/23/2015
 * Time: 11:31 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'Reports';
$this->headTitle($title);
$this->headScript()->appendFile($this->basePath() . '/js/Chart.min.js');
?>
<h1><?= $title ?></h1>
<script type="text/javascript">
    $('document').ready(function(){
        var data = {
            labels: <?= json_encode($labels); ?>,
            datasets: [
                {
                    label: "Income",
                    fillColor: "#339966",
                    strokeColor: "#449977",
                    highlightFill: "#449977",
                    data: <?= json_encode($receivable); ?>
                },
                {
                    label: "Expense",
                    fillColor: "rgba(255,50,50,1.0)",
                    strokeColor: "#FF3333",
                    highlightFill: "#FF4444",
                    data: <?= json_encode($payable); ?>
                }
            ]
        };

        var options = {
            scaleShowGridLines : true,
            scaleGridLineColor : "#e1e1e1",
            scaleGridLineWidth : 1,
            scaleShowHorizontalLines: true,
            scaleShowVerticalLines: true,
            barShowStroke : true,
            barStrokeWidth : 1,
            barValueSpacing: 5,
            barDatasetSpacing:2,
            legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"
        };

        var ctx = $('#cashFlow').get(0).getContext("2d");
        var cashFlow = new Chart(ctx).Bar(data, options);
        var legend = cashFlow.generateLegend();
        $('#legend').append(legend);
        $("#cashFlow").click(function(evt){
            var activeBars = cashFlow.getBarsAtEvent(evt);
            if(activeBars.length > 0){
                var label = activeBars[0].label;

                if(label.length != 7) return;

                var year = label.split("-")[0];
                var month = label.split("-")[1];
                window.location.href = "<?php echo $this->url('account_report', array('action' => 'detail')) ?>/" + year + "/" + month;
            }
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">Income/Expense Report by MMK</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <canvas id="cashFlow" class="col-md-12"  height="120px"></canvas>
                <div id="legend" style="top: 10px; right:50px;position:absolute;"></div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
    </div>
</div>