<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 7/23/2015
 * Time: 11:31 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'Reports';
$this->headTitle($title);
$this->headScript()->appendFile($this->basePath() . '/js/Chart.min.js');
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<hr/>
<script type="text/javascript">
    $('document').ready(function(){
        var data = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
                {
                    label: "USD",
                    fillColor: "rgba(255,255,255,0.15)",
                    strokeColor: "#FF3333",
                    pointColor: "#FF9999",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "#FA0",
                    data: [65, 59, 80, 81, 56, 55, 40]
                },
                {
                    label: "SGD",
                    fillColor: "rgba(255,255,255,0.15)",
                    strokeColor: "#449977",
                    pointColor: "#33BB99",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "#0A9",
                    data: [28, 48, 40, 19, 86, 27, 90]
                }
            ]
        };

        var options = {
            ///Boolean - Whether grid lines are shown across the chart
            scaleShowGridLines : true,

            //String - Colour of the grid lines
            scaleGridLineColor : "rgba(0,0,0,.05)",

            //Number - Width of the grid lines
            scaleGridLineWidth : 1,

            //Boolean - Whether to show horizontal lines (except X axis)
            scaleShowHorizontalLines: true,

            //Boolean - Whether to show vertical lines (except Y axis)
            scaleShowVerticalLines: true,

            //Boolean - Whether the line is curved between points
            bezierCurve : true,

            //Number - Tension of the bezier curve between points
            bezierCurveTension : 0.4,

            //Boolean - Whether to show a dot for each point
            pointDot : true,

            //Number - Radius of each point dot in pixels
            pointDotRadius : 4,

            //Number - Pixel width of point dot stroke
            pointDotStrokeWidth : 1,

            //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
            pointHitDetectionRadius : 20,

            //Boolean - Whether to show a stroke for datasets
            datasetStroke : true,

            //Number - Pixel width of dataset stroke
            datasetStrokeWidth : 2,

            //Boolean - Whether to fill the dataset with a colour
            datasetFill : true,

            //String - A legend template
            legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"

        };

        var ctx = $('#cashFlow').get(0).getContext("2d");
        var cashFlow = new Chart(ctx).Line(data, options);
    });
</script>
<div class="row">
    <canvas id="cashFlow" class="col-md-12"  height="150px"></canvas>
</div>