
<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/24/2015
 * Time: 5:08 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
/**
 * Created by PhpStorm.
 * User:NyanTun
 * Date:3/26/2015
 * Time:2:04AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Constants";
$this->headTitle($title);
$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath() . '/codemirror/lib/codemirror.css')
    ->appendStylesheet($this->basePath() . '/codemirror/theme/mbo.css');
$this->headScript()->appendFile($this->basePath() . '/codemirror/lib/codemirror.js')
    ->appendFile($this->basePath() . '/codemirror/mode/javascript/javascript.js');
?>
<h1><?php echo $title;?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $('.code-value').each(function() {
            var code = $(this).html(),
                unescaped = $('<div/>').html(code).text();

            $(this).empty();

            var jsonEditor = CodeMirror(this, {
                value: unescaped,
                mode: 'javascript',
                lineNumbers: !$(this).is('.inline'),
                readOnly: true,
                theme: 'mbo'
            });
            jsonEditor.setSize('100%', '120px');
        });

        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url : '<?php echo $this->url('constant', array('action' => 'jsonDelete')) ?>',
                    data : $('input[name="chkId[]"]:checked'),
                    type : 'POST',
                    success : function(data){
                        if(data.message == "success"){
                            window.location.href = "<?php echo $this->url('constant'); ?>"
                        }else{
                            alert(data.message);
                        }
                    }
                });
            }
        });

        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });
        $('input[name="chkId[]"]').change(function(){
            var total = $('input[name="chkId[]"]').length;
            var checks = $('input[name="chkId[]"]:checked').length;
            if(total == checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('constantFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("constant", array('action' => 'detail', 'id' => 0)); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('constant', array('action' => 'export')); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                    $columns = array(
                        array(
                            'type' => 'checkbox',
                            'value' => array('id' => 'chkAll'),
                            'attr' => array('class' => 'text-center', 'width' => '50px'),
                        ),
                        array(
                            'type' => 'db',
                            'value' => array(
                                'title' => 'Constant Name',
                                'col' => 'name',
                            ),
                            'attr' => array('width' => '230px'),
                        ),
                        array(
                            'type' => 'db',
                            'value' => array(
                                'title' => 'Group Code',
                                'col' => 'group_code',
                            ),
                            'attr' => array('width' => '230px'),
                        ),
                        array(
                            'type' => 'db',
                            'value' => array(
                                'title' => 'Value',
                                'col' => 'value',
                            )
                        ),
                    );

                    echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php foreach($paginator as $constant) : ?>
                    <tr>
                        <td class=""text-center">
                            <div class="checkbox" style="margin:0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($constant->constantId); ?>" />
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('constant', array('action' => 'detail', 'id' => $constant->constantId)); ?>" title="edit">
                                <?php echo $this->escapeHtml($constant->name); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($constant->group_code);?>
                        </td>
                        <td>
                            <div class="code-value"><?= $constant->value; ?></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route' => 'constant',
                'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>

