<?php
/**
 *@var $this Zend\View\Renderer\PhpRenderer;
 **/

$title="Companies";
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                console.log($('input[name="chkId[]"]:checked'));
                $.ajax({
                    url:'<?php echo $this->url('cr_company', array('action'=>'jsonDelete'))?>',
                    data:$('input[name="chkId[]"]:checked'),
                    type:'POST',
                    success:function(data){
                        console.log(data);
                        if(data.message=="success"){
                            window.location.href="<?php echo $this->url('cr_company')?>"
                        }else{
                            alert(data.message);
                        }
                    }
                });
            }
        });
        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });

        $('input[name="chkId[]"]').change(function(){
            var total=$('input[name="chkId[]"]').length;
            var checks=$('input[name="chkId[]"]:checked').length;

            if(total==checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('companyFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("cr_company", array('action'=>'detail', 'id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('cr_company', array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th width="50px">
                            <div class="checkbox" style="...">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" id="chkAll"/>
                                </label>
                            </div>
                        </th>
                        <th width="250px">
                            <?php echo $this->gridHeaderCell('Company Name', 'name');?>
                        </th>
                        <th width="180px">
                            <?php echo $this->gridHeaderCell('Phone', 'phone');?>
                        </th>
                        <th width="250px">
                            <?php echo $this->gridHeaderCell('Website', 'website');?>
                        </th>
                        <th width="100px">
                            <?php echo $this->gridHeaderCell('Type', 'type');?>
                        </th>
                        <th width="80px">
                            <?php echo $this->gridHeaderCell('Status','status');?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $company):?>
                    <tr>
                        <td>
                            <div class="checkbox" style="...">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($company->companyId);?>"/>
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cr_company', array('action'=>'detail','id'=>$company->companyId));?>" title="edit">
                                <?php echo $this->escapeHtml($company->name);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($company->phone);?>
                        </td>
                        <td>
                            <a href="<?php echo  'http://' . str_replace('http://', '', $company->website); ?>" target="_blank">
                            <?php echo $this->escapeHtml($company->website);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->constantConverter($company->type, 'company_types'); ?>
                        </td>
                        <td>
                            <?php echo $this->constantConverter($company->status, 'default_status'); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route'=>'cr_company', 'sort'=>$sort, 'sortBy'=>$sortBy));?>
        </div>
    </div>
</div>
