<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 1/16/2015
 * Time: 3:55 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $filter Zend\InputFilter\InputFilter
 */
$title = 'Department';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/treeview.css');
$this->headScript()->prependFile($this->basePath() . '/js/treeview.js')
    ->prependFile($this->basePath() . '/js/bootstrap3-typeahead.js');
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <?php echo $this->formTreeView($departments, $id); ?>
    </div>
    <div class="col-md-8">
        <script type="text/javascript">
            $(function(){
                $.get('<?php echo $this->url('hr_department', array('action' => 'jsonAll')); ?>', function(data){
                    $('#parentDepartment #typeahead').typeahead({source: data, afterSelect:function(item){
                        var currentId = parseInt($("input[name=departmentId]").val());
                        if(item.departmentId == currentId && currentId > 0){
                            alert("Parent can't same with current department.");
                            $("input[name=parentId]").val("");
                            return;
                        }
                        $("input[name=parentId]").val(item.departmentId);
                    }});
                });
            });
        </script>
        <?php
        echo $this->form()->openTag($form);
        echo $this->formHorizontal($form->get('departmentId'));
        echo $this->formHorizontal($form->get('name'));
        echo $this->formHorizontal($form->get('description'));
        echo $this->formHorizontal($form->get('group_code'));
        ?>
        <div class="form-group">
            <label class="control-label col-sm-3">Parent Department</label>
            <div class="col-sm-9" id="parentDepartment">
                <script type="text/javascript">
                    department_chose = function(value){
                        var currentId = parseInt($("input[name=departmentId]").val());
                        if(value == currentId && currentId > 0){
                            alert("Parent can't same with current department.");
                            $("input[name=parentId]").val("");
                            return true;
                        }
                        $('input[name=parentId]').val(value);
                    }
                </script>
                <?= $this->formHidden($form->get('parentId')); ?>
                <?= $this->partial('shared/tree_chooser.phtml', array('data' => $departments,
                    'name' => 'departmentPicker', 'callback' => 'department_chose',
                    'active' => $form->get('parentId')->getValue())) ?>
            </div>
        </div>

        <?php echo $this->formHorizontal($form->get('priority')); ?>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <a href="<?php echo $this->url("hr_department"); ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-file"></span>
                    New
                </a>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    Save
                </button>
                <?php if($this->isEdit): ?>
                <a href="<?php echo $this->url("hr_department", array('action' => 'index', 'id' => $id)); ?>?action=clone" class="btn btn-warning">
                    <span class="glyphicon glyphicon-copy"></span>
                    Clone
                </a>
                <a href="<?php echo $this->url("hr_department", array('action' => 'index', 'id' => $id)); ?>?action=delete"
                   class="btn btn-danger" onclick="return confirm('Are you sure to delete?')">
                    <span class="glyphicon glyphicon-trash"></span>
                    Remove
                </a>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

