<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 2/16/2015
 * Time: 3:53 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $form \Zend\Form\Form
 */

$title = 'Welcome!';
$this->headTitle($title);
$user_error = $form->getMessages('username');
$password_error = $form->getMessages('password');
if(empty($message) && !empty($form->getMessages('isHuman'))){
    $message = $form->getMessages('isHuman')['badCaptcha'];
}
?>
<script type="text/javascript">
    $('document').ready(function(){
        $('body').css('background','#353535 url(<?php echo $this->basePath() . '/img/dark_wood.png'; ?>)');
        $('body').css('color', '#ffffff');
    });
</script>
<h1 class="text-center"><?php echo $title; ?></h1>
<hr />
<div class="container" style="margin: 90px 0;">
    <div class="col-md-5 col-md-offset-3">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('auth'));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <?php if(!empty($message)) : ?>
                    <div class="alert alert-warning alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <?php echo $message; ?>
                    </div>
                <?php endif;?>
            </div>
        </div>

        <div class="form-group<?php echo empty($user_error) ? '' : ' has-error';?>">
            <label class="col-sm-3 control-label">
                <span class="glyphicon glyphicon-user"></span>
            </label>
            <div class="col-sm-9">
                <?php echo $this->formText($form->get('username')); ?>
            </div>
        </div>
        <div class="form-group<?php echo empty($password_error) ? '' : ' has-error';?>">
            <label class="col-sm-3 control-label">
                <span class="glyphicon glyphicon-lock"></span>
            </label>
            <div class="col-sm-9">
                <?php echo $this->formPassword($form->get('password')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <?php echo $this->formCaptcha($form->get('isHuman')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-block btn-success">
                    <span class="glyphicon glyphicon-log-in"></span>
                    Entrance
                </button>
            </div>
        </div>
        <?php echo $this->formHorizontal($form->get('remember')); ?>
        <?php
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<hr />
<p align="center">Copyright &copy; 2011 - <?php echo date('Y') ?> by SUNDEW MYANMAR.
    <br /><?php echo $this->translate('All rights reserved.') ?>
</p>