<?php $this->layout('layout/error-layout'); ?>
<h1><?php echo $this->translate('An error occurred') ?></h1>
<h2><?php echo $this->message ?></h2>
<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
    <hr />
    <h3><?php echo get_class($this->exception); ?></h3>
    <dl>
        <dt><?php echo $this->translate('Message') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->escapeHtml($this->exception->getMessage()) ?></pre>
        </dd>
    </dl>
<?php endif; ?>



