<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 6/19/2015
 * Time: 3:06 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = "Leave";
$this->headTitle($title);
?>
<h1><?php echo $title;?></h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('leaveFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("hr_leave",array('action'=>'detail','id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('hr_leave',array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('Date','date');?>
                    </th>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('Code','staffCode');?>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Name','staffName');?>
                    </th>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('Leave','leaveType');?>
                    </th>
                    <th>
                        <?php echo $this->gridHeaderCell('Description','description');?>
                    </th>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('status','status');?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $leave): ?>
                    <?php if($leave->status == 'Requested'): ?>
                    <tr class="info">
                    <?php else: ?>
                    <tr>
                    <?php endif; ?>
                        <td>
                            <a href="<?php echo $this->url('hr_leave', array('action' => 'detail', 'id' => $leave->leaveId)); ?>" title="edit">
                                <?= $this->escapeHtml($leave->date); ?>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('hr_leave', array('action' => 'detail', 'id' => $leave->leaveId)); ?>" title="edit">
                                <?php echo $this->escapeHtml($leave->staffCode); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($leave->staffName); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($leave->leaveType); ?>
                        </td>
                        <td>
                            <?= $this->escapeHtml($leave->description); ?>
                        </td>
                        <td>
                            <?= $this->escapeHtml($leave->status); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route' => 'hr_leave',
                'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>