<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 5/25/2015
 * Time: 4:41 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */

$title="Balance sheet (Detail)";
$this->headTitle($title);
$main_url = $this->url('account_balance', array('action' => 'detail', 'id' => $id));
?>
<h1><?php echo $title;?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("[data-toggle=popover]").popover();
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('balanceFilter',$main_url); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <?php echo $this->backButton() ?>
                        <a href="<?php echo $this->url('account_balance',array('action'=>'export', 'id' => $id));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                $columns = array(
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Voucher No',
                            'col' => 'voucherNo',
                            'url' => $main_url,
                        ),
                        'attr' => array('width' => '150px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Date',
                            'col' => 'approvedDate',
                            'url' => $main_url,
                        ),
                        'attr' => array('width' => '100px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Requester',
                            'col' => 'requester',
                            'url' => $main_url,
                        ),
                        'attr' => array('width' => '200px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Description',
                            'col' => 'description',
                            'url' => $main_url,
                        ),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Amount',
                            'col' => 'amount',
                            'url' => $main_url,
                        ),
                        'attr' => array('width' => '180px'),
                    ),
                    array(
                        'type' => 'custom',
                        'value' => 'Status',
                        'attr' => array('width' => '80px'),
                    ),
                );

                echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php foreach($paginator as $voucher):?>
                    <?php
                    $status = $this->constantConverter($voucher->status, 'account_status');
                    $class = '';
                    switch($voucher->status){
                        case 'A':
                            $class = 'info';
                            break;
                        case 'C':
                            $class = 'warning';
                            break;
                        case 'F':
                            $class = 'success';
                            break;
                        default:
                            $status = 'Error';
                            break;
                    }?>
                    <tr class="<?php echo $class; ?>">
                        <td>
                            <a href="<?php echo $this->url('account_voucher', array('action' => 'detail', 'voucher' => $voucher->voucherNo)); ?>" title="edit">
                                <?php echo $this->escapeHtml($voucher->voucherNo); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo substr($this->escapeHtml($voucher->approvedDate),0,10); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->requester); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->description); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->amount) . ' ' . $this->escapeHtml($voucher->currency); ?>
                        </td>
                        <td>
                            <?php if($voucher->status == 'C') : ?>
                                <a data-original-title="Reason" href="#" class="btn btn-block btn-warning btn-xs" data-toggle="popover"
                                   title="Reason" data-content="<?php echo $voucher->reason; ?>" role="button" data-placement="bottom">
                                    Cancel
                                </a>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($status); ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array(
                'url' => $main_url,
                'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>

