<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 7/30/2015
 * Time: 11:50 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title = 'Payroll List';
$this->headTitle($title);
$this->headScript()
    ->appendFile($this->basePath() . '/js/math.min.js');
?>
<h1><?php echo $title; ?></h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('payrollFilter'); ?>
            </div>
            <div class="col-md-9">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("hr_payroll", array('action'=>'process'));?>" class="btn btn-primary">
                            <span class="glyphicon glyphicon-tasks"></span>
                            Process
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                $columns = array(
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Form',
                            'col' => 'fromDate',
                        ),
                        'attr' => array('class' => 'text-center', 'width' => '70px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'To',
                            'col' => 'toDate',
                        ),
                        'attr' => array('class' => 'text-center', 'width' => '70px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Staff',
                            'col' => 'staffName',
                        ),
                        'attr' => array('width' => '120px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Salary',
                            'col' => 'salary',
                        ),
                        'attr' => array('width' => '100px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'M_WD',
                            'col' => 'm_wd',
                        ),
                        'attr' => array('class' => 'text-center', 'width' => '60px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'S_WD',
                            'col' => 's_wd',
                        ),
                        'attr' => array('class' => 'text-center', 'width' => '60px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'L',
                            'col' => 'leave',
                        ),
                        'attr' => array('class' => 'text-center', 'width' => '60px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Late',
                            'col' => 'Late',
                        ),
                        'attr' => array('width' => '100px'),
                    ),
                    array(
                        'type' => 'custom',
                        'value' => 'Net',
                        'attr' => array('width' => '120px')
                    ),
                    array(
                        'type' => 'custom',
                        'value' => 'Print',
                        'attr' => array('class' => 'text-center', 'width' => '50px')
                    )
                );

                echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php
                    foreach($paginator as $payroll):
                    if($payroll->s_wd <= 0) $payroll->s_wd = 1;
                ?>
                    <tr>
                        <td class="text-center"><?= $payroll->fromDate ?></td>
                        <td class="text-center"><?= $payroll->toDate ?></td>
                        <td><?= $this->escapeHtml($payroll->staffName . '(' . $payroll->staffCode . ')') ?></td>
                        <td><?= $this->escapeHtml($payroll->salary . ' ' . $payroll->Currency) ?></td>
                        <td class="text-center"><?= $payroll->m_wd ?></td>
                        <td class="text-center"><?= $payroll->s_wd ?></td>
                        <td class="text-center"><?= $payroll->leave ?></td>
                        <td><?= $this->escapeHtml($payroll->Late); ?></td>
                        <td>
                            <script type="text/javascript">
                                var data = {
                                    S: <?= $payroll->salary ?>,
                                    M: <?= $payroll->m_wd; ?>,
                                    P: parseFloat(<?= $payroll->salary / $payroll->s_wd; ?>),
                                    W: parseFloat(<?= $payroll->s_wd ?>),
                                    L: parseFloat(<?= $payroll->leave ?>),
                                    A: parseFloat(<?= $payroll->absent ?>)
                                };

                                $.each(<?= $payroll->Late ?>, function(key, value){
                                    console.log(value);
                                    data[key] = parseInt(value);
                                });

                                var result = math.eval('<?= $payroll->formula ?>', data);
                                document.write(math.round(result, 2) + ' ' + '<?= $payroll->Currency ?>');
                            </script>

                        </td>
                        <td class="text-center">
                            <a href="<?= $this->url('hr_payroll', array('action' => 'detail', 'id' => $payroll->payrollId)); ?>"
                               title="Show slip" class="btn btn-sm btn-info">
                                <span class="glyphicon glyphicon-print"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding','shared/paginator.phtml', array('route'=>'hr_payroll', 'sort'=>$sort, 'sortBy'=>$sortBy)); ?>
        </div>
    </div>
</div>