<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 7/30/2015
 * Time: 11:50 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title = 'Payroll List';
$this->headTitle($title);
$this->headScript()
    ->appendFile($this->basePath() . '/js/math.min.js');
?>
<h1><?php echo $title; ?></h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="text-right">
            <div class="btn-group">
                <a href="<?php echo $this->url("hr_payroll", array('action'=>'process'));?>" class="btn btn-primary">
                    <span class="glyphicon glyphicon-tasks"></span>
                    Process
                </a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="70px" class="text-center">
                        <?php echo $this->gridHeaderCell('From','fromDate');?>
                    </th>
                    <th width="70px" class="text-center">
                        <?php echo $this->gridHeaderCell('To','toDate');?>
                    </th>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('Staff','staffName');?>
                    </th>
                    <th width="100px">
                        <?php echo $this->gridHeaderCell('Salary','salary');?>
                    </th>
                    <th width="60px" class="text-center">
                        <?php echo $this->gridHeaderCell('M_WD','m_wd');?>
                    </th>
                    <th width="60px" class="text-center">
                        <?php echo $this->gridHeaderCell('S_WD','s_wd');?>
                    </th>
                    <th width="60px" class="text-center">
                        <?php echo $this->gridHeaderCell('L','leave');?>
                    </th>
                    <th width="100px">
                        <?php echo $this->gridHeaderCell('Late','Late');?>
                    </th>
                    <th width="120px">
                        Net
                    </th>
                    <th width="50px" class="text-center">
                        Print
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $payroll):?>
                    <tr>
                        <td class="text-center"><?= $payroll->fromDate ?></td>
                        <td class="text-center"><?= $payroll->toDate ?></td>
                        <td><?= $this->escapeHtml($payroll->staffName . '(' . $payroll->staffCode . ')') ?></td>
                        <td><?= $this->escapeHtml($payroll->salary . ' ' . $payroll->Currency) ?></td>
                        <td class="text-center"><?= $payroll->m_wd ?></td>
                        <td class="text-center"><?= $payroll->s_wd ?></td>
                        <td class="text-center"><?= $payroll->leave ?></td>
                        <td><?= $this->escapeHtml($payroll->Late); ?></td>
                        <td>
                            <script type="text/javascript">
                                var data = {
                                    S: <?= $payroll->salary ?>,
                                    M: <?= $payroll->m_wd; ?>,
                                    P: parseFloat(<?= $payroll->salary / $payroll->s_wd; ?>),
                                    W: parseFloat(<?= $payroll->s_wd ?>),
                                    L: parseFloat(<?= $payroll->leave ?>),
                                    A: parseFloat(<?= $payroll->absent ?>)
                                };

                                $.each(<?= $payroll->Late ?>, function(key, value){
                                    data[key] = parseInt(value);
                                });

                                var result = math.eval('<?= $payroll->formula ?>', data);
                                document.write(math.round(result, 2) + ' ' + '<?= $payroll->Currency ?>');
                            </script>

                        </td>
                        <td class="text-center">
                            <a href="<?= $this->url('hr_payroll', array('action' => 'detail', 'id' => $payroll->payrollId)); ?>"
                               title="Show slip" class="btn btn-sm btn-info">
                                <span class="glyphicon glyphicon-print"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding','shared/paginator.phtml', array('route'=>'hr_payroll', 'sort'=>$sort, 'sortBy'=>$sortBy)); ?>
        </div>
    </div>
</div>