<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 6/25/2015
 * Time: 2:16 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'Payroll process';
$this->headTitle($title);
?>
<script type="text/javascript">
    $('document').ready(function(){

    });
</script>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class="panel panel-default">
    <div class="panel-heading">
    </div>
    <div class="panel-body">
    </div>
    <div class="panel-footer">
    </div>
</div>