 <?php
 /** Created by PhpStorm */

 /**
  * Created by PhpStorm
  * User:NyanTun
  * Date:4/22/2015
  * Time:11:04 AM
  * Zend Code Completion
     *@var $this Zend\View\Renderer\PhpRenderer;
     **/
 $title="Staffs";
 $this->headTitle($title);
?>

 <h1><?php echo $title; ?></h1>

 <script type="text/javascript">
     $(document).ready(function(){
         $("button#btnDelete").click(function(){
             if(confirm('Are you sure to delete selected records?')){
                 $.ajax({
                     url:'<?php echo $this->url('hr_staff',array('action'=>'jsonDelete'))?>',
                     data:$('input[name="chkId[]"]:checked'),
                     type:'POST',
                     success:function(data){
                         console.log(data);
                         if(data.message=="success"){
                             window.location.href="<?php echo $this->url('hr_staff');?>"
                         }else{
                             alert(data.message);
                         }
                     }
                 });
             }
         });
         $("input#chkAll").change(function(){
             if($(this).checkbox('isChecked')){
                 $('input[name="chkId[]"]').checkbox('check');
             }else{
                 $('input[name="chkId[]"]').checkbox('uncheck');
             }
         });
         $('input[name="chkId[]"]').change(function(){
             var total=$('input[name="chkId[]"]').length;
             var checks=$('input[name="chkId[]"]:checked').length;
             if(total==checks){
                 $("input#chkAll").checkbox('check');
             }else{
                 $("input#chkAll").checkbox('uncheck');
             }
         });
     });
 </script>
 <div class="panel panel-default">
     <div class="panel-heading">
         <div class="row">
             <div class="col-md-3">
                 <?php echo $this->gridFilter('staffFilter'); ?>
             </div>
             <div class="col-md-4 col-md-offset-5">
                 <div class="text-right">
                     <div class="btn-group">
                         <a href="<?php echo $this->url("hr_staff", array('action'=>'detail', 'id'=>0));?>" class="btn btn-default">
                             <span class="glyphicon glyphicon-file"></span>
                             New
                         </a>
                         <a href="<?php echo $this->url('hr_staff', array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                             Export
                         </a>
                         <button type="button" id="btnDelete" class="btn btn-danger">
                             <span class="glyphicon glyphicon-trash"></span>
                             Delete
                         </button>
                     </div>
                 </div>
             </div>
         </div>
         </div>
     <div class="panel-body">
         <div class="grid">
             <table class="table table-bordered table-striped table-hover">
                 <thead>
                    <tr>
                        <th width="50px">
                            <div class="checkbox">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" id="chkAll"/>
                                </label>
                            </div>
                        </th>
                        <th width="150px">
                            <?php echo $this->gridHeaderCell('Staff Code','staffCode');?>
                        </th>
                        <th>
                            <?php echo $this->gridHeaderCell('Staff Name','staffName');?>
                        </th>
                        <th width="90px">
                            <?php echo $this->gridHeaderCell('Leave','Leave');?>
                        </th>
                        <th width="120px">
                            <?php echo $this->gridHeaderCell('P-Date','PermanentDate');?>
                        </th>
                        <th width="100px">
                            <?php echo $this->gridHeaderCell('Status','status');?>
                        </th>
                    </tr>
                 </thead>
                 <tbody>

                 <?php foreach($paginator as $staff):?>
                 <tr>
                     <td>
                         <div class="checkbox" style="...">
                             <label class="checkbox-custom" data-initialize="checkbox">
                                 <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($staff->staffId);?>" />
                             </label>
                         </div>
                     </td>
                     <td>
                         <a href="<?php echo $this->url('hr_staff', array('action'=>'detail', 'id'=>$staff->staffId));?>" title="edit">
                             <?php echo $this->escapeHtml($staff->staffCode);?>
                         </a>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->staffName);?>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->Leave);?>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->PermanentDate);?>
                     </td>
                     <td>
                         <?php
                         switch($staff->Status)
                         {
                             case'A':
                                 echo 'Active';
                                 break;
                             case 'D':
                                 echo 'Inactive';
                                 break;
                             default:
                                 echo 'Invalid';
                                 break;
                         }
                         ?>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
             </table>
         </div>
     </div>
     <div class="panel-footer">
         <div class="text-center">
             <?php echo $this->paginationControl($paginator, 'Sliding','shared/paginator.phtml', array('route'=>'hr_staff', 'sort'=>$sort, 'sortBy'=>$sortBy)); ?>
         </div>
     </div>
     </div>