 <?php
 /** Created by PhpStorm */

 /**
  * Created by PhpStorm
  * User:NyanTun
  * Date:4/22/2015
  * Time:11:04 AM
  * Zend Code Completion
     *@var $this Zend\View\Renderer\PhpRenderer;
     **/
 $title="Staffs";
 $this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<script type="text/javascript">
 $(document).ready(function(){
     $("button#btnDelete").click(function(){
         if(confirm('Are you sure to delete selected records?')){
             $.ajax({
                 url:'<?php echo $this->url('hr_staff',array('action'=>'apiDelete'))?>',
                 data:$('input[name="chkId[]"]:checked'),
                 type:'POST',
                 success:function(data){
                     window.location.href="<?php echo $this->url('hr_staff');?>"
                 },
                 error: function(response){
                     var data = response.reponseJSON;
                     alert(data.status.message);
                 }
             });
         }
     });
     $("input#chkAll").change(function(){
         if($(this).checkbox('isChecked')){
             $('input[name="chkId[]"]').checkbox('check');
         }else{
             $('input[name="chkId[]"]').checkbox('uncheck');
         }
     });
     $('input[name="chkId[]"]').change(function(){
         var total=$('input[name="chkId[]"]').length;
         var checks=$('input[name="chkId[]"]:checked').length;
         if(total==checks){
             $("input#chkAll").checkbox('check');
         }else{
             $("input#chkAll").checkbox('uncheck');
         }
     });
 });
</script>
<div class="panel panel-default">
     <div class="panel-heading">
         <div class="row">
             <div class="col-md-3">
                 <?php echo $this->gridFilter('staffFilter'); ?>
             </div>
             <div class="col-md-4 col-md-offset-5">
                 <div class="text-right">
                     <div class="btn-group">
                         <a href="<?php echo $this->url("hr_staff", array('action'=>'detail', 'id'=>0));?>" class="btn btn-default">
                             <span class="glyphicon glyphicon-file"></span>
                             New
                         </a>
                         <a href="<?php echo $this->url('hr_staff', array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                             Export
                         </a>
                         <button type="button" id="btnDelete" class="btn btn-danger">
                             <span class="glyphicon glyphicon-trash"></span>
                             Delete
                         </button>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <div class="panel-body">
         <div class="grid">
             <table class="table table-bordered table-striped table-hover">
                 <?php
                 $columns = array(
                     array(
                         'type' => 'checkbox',
                         'value' => array('id' => 'chkAll'),
                         'attr' => array('class' => 'text-center', 'width' => '50px'),
                     ),
                     array(
                         'type' => 'db',
                         'value' => array(
                             'title' => 'Staff Code',
                             'col' => 'staffCode',
                         ),
                         'attr' => array('width' => '150px'),
                     ),
                     array(
                         'type' => 'db',
                         'value' => array(
                             'title' => 'Staff Name',
                             'col' => 'staffName',
                         ),
                     ),
                     array(
                         'type' => 'db',
                         'value' => array(
                             'title' => 'Leave',
                             'col' => 'Leave',
                         ),
                         'attr' => array('width' => '90px'),
                     ),
                     array(
                         'type' => 'db',
                         'value' => array(
                             'title' => 'P-Date',
                             'col' => 'PermanentDate',
                         ),
                         'attr' => array('width' => '120px'),
                     ),
                     array(
                         'type' => 'db',
                         'value' => array(
                             'title' => 'Status',
                             'col' => 'status',
                         ),
                         'attr' => array('width' => '100px'),
                     ),
                     array(
                         'type' => 'custom',
                         'value' => 'Report',
                         'attr' => array('width' => '80px'),
                     )
                 );
                 echo $this->gridHeader($columns);
                 ?>
                 <tbody>
                 <?php foreach($paginator as $staff):?>
                 <tr>
                     <td class="text-center">
                         <div class="checkbox" style="...">
                             <label class="checkbox-custom" data-initialize="checkbox">
                                 <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($staff->staffId);?>" />
                             </label>
                         </div>
                     </td>
                     <td>
                         <a href="<?php echo $this->url('hr_staff', array('action'=>'detail', 'id'=>$staff->staffId));?>" title="edit">
                             <?php echo $this->escapeHtml($staff->staffCode);?>
                         </a>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->staffName);?>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->annual_leave);?>
                     </td>
                     <td>
                         <?php echo $this->escapeHtml($staff->permanentDate);?>
                     </td>
                     <td>
                         <?php echo $this->constantConverter($staff->status, 'default_status'); ?>
                     </td>
                     <td class="center">
                        <a href="<?php echo $this->url('hr_staff', array('action' => 'report', 'id' => $staff->staffId)); ?>"
                           class="btn btn-info btn-xs" title="Staff Report">
                            <span class="fa fa-bar-chart"></span>
                        </a>
                     </td>
                 </tr>
                 <?php endforeach; ?>
                 </tbody>
             </table>
         </div>
     </div>
     <div class="panel-footer">
         <div class="text-center">
             <?php echo $this->paginationControl($paginator, 'Sliding','shared/paginator.phtml', array('route'=>'hr_staff', 'sort'=>$sort, 'sortBy'=>$sortBy)); ?>
         </div>
     </div>
 </div>