<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 7/24/2015
 * Time: 11:30 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'Project Management';
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('projectFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("pm_project",array('action'=>'detail','id'=>0));?>"
                           class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('pm_project',array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="50px">
                        <div class="checkbox" style="margin: 0">
                            <label class="checkbox-custom" data-initialize="checkbox">
                                <input type="checkbox" id="chkAll" />
                            </label>
                        </div>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Code','code');?>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Name','name');?>
                    </th>
                    <th>
                        <?php echo $this->gridHeaderCell('Description','description');?>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Start','startDate');?>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('End','endDate');?>
                    </th>
                    <th width="160px">
                        <?php echo $this->gridHeaderCell('Status','status');?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $project):?>
                    <tr>
                        <td>
                            <div class="checkbox" style="margin: 0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($project->projectId);?>" />
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('pm_project', array('action' => 'detail', 'id' => $project->projectId)); ?>" title="edit">
                                <?php echo $this->escapeHtml($project->code); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($project->name); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($project->description); ?>
                        </td>
                        <td>
                            <?php echo $project->startDate; ?>
                        </td>
                        <td>
                            <?php echo $project->endDate; ?>
                        </td>
                        <td>
                            <?php echo $this->constantConverter($project->status, 'default_status'); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml',
                array('route' => 'pm_project', 'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>