<?php
/**
 * Created by PhpStorm.
 * User: Htoonlin
 * Date: 8/15/2015
 * Time: 5:49 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$this->headTitle($title);
$this->headScript()->appendFile($this->basePath() . '/js/Chart.min.js');
?>
<script type="text/javascript">
    $().ready(function(){

        var createReport = function (id, url){
            var ctx = $(id).find('#chartBox').get(0).getContext("2d");
            $.get(url, function(res){
                var chart;
                var data = res.data;
                /* Generate Report */
                if(data.type == 'Pie'){
                    chart = new Chart(ctx).Pie(data.data, data.options);
                }else if(data.type == 'Bar'){
                    chart = new Chart(ctx).Bar(data.data, data.options);
                }

                /* Report Title */
                var title = '<i class="' + data.icon + '"></i> ' + data.title;
                $(id).find('#reportTitle').html(title);

                /* Report Labeling */
                var legend = chart.generateLegend();
                $(id).find('#legend').append(legend);
            });
        };

        /* Progress Report */
        createReport('#progressReport', '<?php echo $this->url('pm_report', array('action' => 'progress', 'id' => $projectId)); ?>');

        /* Workload Report */
        createReport('#workloadReport', '<?php echo $this->url('pm_report', array('action' => 'workload', 'id' => $projectId)); ?>');

        /* Overdue Report */
        createReport('#overdueReport', '<?php echo $this->url('pm_report', array('action' => 'overdue', 'id' => $projectId)); ?>');

    });
</script>
<div class="row" style="margin-top: 15px;">
    <div class="col-md-9">
        <h1 style="margin:0;font-size:22px;"><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="col-md-3 text-right">
        <?php echo $this->backButton(); ?>
        <a href="<?php echo $this->url('pm_task', array('action' => 'index', 'id' => $projectId)); ?>" class="btn btn-primary">
            <span class="fa fa-check-square"></span>
            Task Detail
        </a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default" id="workloadReport">
            <div class="panel-heading">
                <h4 class="panel-title" id="reportTitle"></h4>
            </div>
            <div class="panel-body">
                <canvas id="chartBox" class="col-sm-12" height="100px"></canvas>
                <div id="legend" style="right:50px;position:absolute;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default" id="progressReport">
            <div class="panel-heading">
                <h4 class="panel-title" id="reportTitle"></h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-7 col-sm-offset-1">
                        <canvas id="chartBox" width="250px" height="250px"></canvas>
                    </div>
                    <div class="col-sm-4">
                        <div id="legend"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default" id="overdueReport">
            <div class="panel-heading">
                <h4 class="panel-title" id="reportTitle"></h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-7 col-sm-offset-1">
                        <canvas id="chartBox" width="250px" height="250px"></canvas>
                    </div>
                    <div class="col-sm-4">
                        <div id="legend"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


