<?php 
/**
 * Created by PhpStorm.
 * User: Htoonlin
 * Date: 8/15/2015
 * Time: 5:49 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'Project Report';
$this->headTitle($title);
$this->headScript()->appendFile($this->basePath() . '/js/Chart.min.js');
?>
<script type="text/javascript">
    $().ready(function(){
        var data = [
            {
                value: 300,
                color:"#F7464A",
                highlight: "#FF5A5E",
                label: "Red"
            },
            {
                value: 50,
                color: "#46BFBD",
                highlight: "#5AD3D1",
                label: "Green"
            },
            {
                value: 100,
                color: "#FDB45C",
                highlight: "#FFC870",
                label: "Yellow"
            }
        ]

        var options = {
            segmentShowStroke : true,
            segmentStrokeColor : "#fff",
            segmentStrokeWidth : 2,
            percentageInnerCutout : 50,
            animationSteps : 100,
            animationEasing : "easeOutBounce",
            animateRotate : true,
            animateScale : false
        }

        var ctx = $('#currentChart').get(0).getContext("2d");
        var currentChart = new Chart(ctx).Pie(data, options);
    });
</script>
<style type="text/css">
    div#thumbnail{
        height: 120px;
    }
</style>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-6">
                        <h4 class="panel-title">
                            <i class="fa fa-2x fa-pie-chart"></i> Progress report for all project
                        </h4>
                    </div>
                    <div class="col-sm-6 text-right">
                        <div class="btn-group">
                            <?php echo $this->backButton(); ?>
                            <a href="<?php echo $this->url('pm_task', array('action' => 'index', 'id' => $projectId)); ?>" class="btn btn-info">
                                <span class="fa fa-check-square"></span>
                                Task List
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <canvas id="currentChart" class="col-sm-6" height="200px"></canvas>
                    <div class="col-sm-6">

                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-block btn-primary" disabled="disabled">
                            <div id="thumbnail">

                            </div>
                            <i class="fa fa-calendar"></i> Progress
                        </button>
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-default btn-block">
                            <div id="thumbnail">

                            </div>
                            <i class="fa fa-calendar"></i> Overdue
                        </button>
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-default btn-block">
                            <div id="thumbnail">

                            </div>
                            <i class="fa fa-calendar"></i> By Staff
                        </button>
                    </div>
                    <div class="col-sm-3">
                        <button type="button" class="btn btn-default btn-block">
                            <div id="thumbnail">

                            </div>
                            <i class="fa fa-calendar"></i> By Date
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

