<?php 
/**
 * Created by PhpStorm.
 * User: Htoonlin
 * Date: 2015-08-20
 * Time: 11:45 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'CEO Preferences';
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<hr/>
<div class="panel panel-default">
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#system" data-toggle="tab">
                    <i class="fa fa-cog"></i> System Info
                </a>
            </li>
            <li>
                <a href="#php" data-toggle="tab">
                    <img src="<?php echo $this->basePath() . '/img/php.gif' ?>" height="20px" /> PHP info
                </a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="system">
                <div style="margin:10px 0;">
                    <div class="panel-group" id="accordion">
                        <?php foreach($settings as $setting) : ?>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#<?php echo $setting['id'] ?>">
                                        <i class="<?php echo $setting['icon']; ?>"></i> <?php echo $setting['title']; ?>
                                    </a>
                                </h4>
                            </div>
                            <div id="<?php echo $setting['id']; ?>" class="panel-collapse collapse<?php echo isset($setting['isOpen']) ? ' in' : ''; ?>">
                                <div class="panel-body">
                                    <?php
                                        if(isset($setting['form'])){
                                            echo '<form';
                                            foreach($setting['form'] as $key => $value){
                                                echo ' ' . $key . '="' . $value . '"';
                                            }
                                            echo '>';
                                        }
                                    ?>
                                    <div class="grid">
                                        <table class="table table-striped table-borderd table-hovered">
                                            <thead>
                                                <tr>
                                                    <th width="35%" class="text-center">
                                                        Key/Description
                                                    </th>
                                                    <th class="text-center">
                                                        Value
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php foreach($setting['data'] as $key => $value): ?>
                                                <tr>
                                                    <td><?php echo $key; ?></td>
                                                    <td><?php echo $value; ?></td>
                                                </tr>
                                                <?php endforeach; ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <?php
                                    if(isset($setting['form'])){
                                        echo '</form>';
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="php">
                <iframe src="<?php echo $this->url('preferences', array('action' => 'php')); ?>"
                        width="100%" height="600px" frameborder="none"
                    style="border:1px solid #ccc;margin:10px 0;">
                </iframe>
            </div>
        </div>
    </div>
</div>

