<?php 
/**
 * Created by PhpStorm.
 * User: Htoonlin
 * Date: 2015-08-20
 * Time: 11:45 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = 'CEO Installation';
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<hr/>
<div>
    <div class="panel-group" id="accordion">
        <?php foreach($settings as $setting) : ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#<?php echo $setting['id'] ?>">
                        <i class="<?php echo $setting['icon']; ?>"></i> <?php echo $setting['title']; ?>
                    </a>
                </h4>
            </div>
            <div id="<?php echo $setting['id']; ?>" class="panel-collapse collapse<?php echo isset($setting['isOpen']) ? ' in' : ''; ?>">
                <div class="panel-body">
                    <?php
                        if(isset($setting['form'])){
                            echo '<form';
                            foreach($setting['form'] as $key => $value){
                                echo ' ' . $key . '="' . $value . '"';
                            }
                            echo '>';
                        }
                    ?>
                    <div class="grid">
                        <table class="table table-striped table-borderd table-hovered">
                            <thead>
                                <tr>
                                    <th width="35%" class="text-center">
                                        Key/Description
                                    </th>
                                    <th class="text-center">
                                        Value
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($setting['data'] as $key => $value): ?>
                                <tr>
                                    <td><?php echo $key; ?></td>
                                    <td><?php echo $value; ?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <?php
                    if(isset($setting['form'])){
                        echo '</form>';
                    }
                    ?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
