 <?php
 /**
     *@var $this Zend\View\Renderer\PhpRenderer;
     **/
     
 $title="Contact";
 $this->headTitle($title);
 ?>

 <h1><?php echo $title; ?></h1>
 <hr/>
 <?php
    $form->setAttribute('action', $this->url('cr_contact', array('action'=>'detail', 'id'=>$id)));
    $form->prepare();
    echo $this->form()->openTag($form);
 ?>

 <div class="col-md-8">
     <?php
     echo $this->formHidden($form->get('contactId'));
     echo $this->formHorizontal($form->get('name'));
     echo $this->formHorizontal($form->get('phone'));
     echo $this->formHorizontal($form->get('tag'));
     echo $this->formHorizontal($form->get('email'));
     echo $this->formHorizontal($form->get('website'));
     echo $this->formHorizontal($form->get('companyId'));
     echo $this->formHorizontal($form->get('address'));
     echo $this->formHorizontal($form->get('notes'));
     echo $this->formHorizontal($form->get('status'));
     ?>
     <div class="form-group">
         <div class="col-sm-offset-3 col-sm-9">
             <button type="submit" value="Save" class="btn btn-primary">
                 <span class="glyphicon glyphicon-floppy-save"></span>
                 Save
             </button>
             <?php if($isEdit):?>
                 <a href="<?php echo $this->url('cr_contact', array('action'=>'detail', 'id'=>$id));?>?action=clone"
                     class="btn btn-warning">
                     <span class="glyphicon glyphicon-copy"></span>
                     Clone
                 </a>
                 <a onclick="return confirm('Are you sure to delete?')" href="<?php echo $this->url('cr_contact', array('action'=>'delete', 'id'=>$id));?>" class="btn btn-danger">
                     <span class="glyphicon glyphicon-trash"></span>
                     Remove
                 </a>
             <?php endif; ?>
             <?php echo $this->backButton(); ?>
         </div>
     </div>
 </div>

 <?php
    echo $this->form()->closeTag();
 ?>
