<?php
/**
 *@var $this Zend\View\Renderer\PhpRenderer;
 **/
$title="Contacts";
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("#txtFilter").keydown(function(e){
            if(e.which==13){
                var filter=$(this).val();
                window.location.href='<?php echo $this->url().'?page='. $page. '&filter=';?>'+filter+'<?php echo '&sort='.$sort.'&by='.$sortBy; ?>'

            }
        });
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url:'<?php echo $this->url('cr_contact', array('action'=>'jsonDelete'))?>',
                    data:$('input[name="chkId[]"]:checked'),
                    type:'POST',
                    success:function(data){
                        console.log(data);
                        if(data.message=="success"){
                            window.location.href="<?php echo $this->url('cr_contact')?>"
                        }else{
                            alert(data.message);
                        }
                    }
                });
            }
        });
        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });

        $('input[name="chkId[]"]').change(function(){
            var total=$('input[name="chkId[]"]').length;
            var checks=$('input[name="chkId[]"]:checked').length;

            if(total==checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <div class="input-group">
                     <span class="input-group-addon">
                         <span class="glyphicon glyphicon-search"></span>
                     </span>
                    <input type="text" class="form-control" id="txtFilter" value="<?php echo $filter;?>"/>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("cr_contact", array('action'=>'detail', 'id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('cr_contact', array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                <tr>
                    <th width="50px">
                        <div class="checkbox" style="...">
                            <label class="checkbox-custom" data-initialize="checkbox">
                                <input type="checkbox" id="chkAll"/>
                            </label>
                        </div>
                    </th>
                    <th>
                        <?php echo $this->gridHeaderCell('Contact Name', 'name', $filter, $page, $sort, $sortBy);?>
                    </th>
                    <th width="200px">
                        <?php echo $this->gridHeaderCell('Phone', 'phone', $filter, $page, $sort, $sortBy);?>
                    </th>
                    <th width="200px">
                        <?php echo $this->gridHeaderCell('Email', 'email', $filter, $page, $sort, $sortBy);?>
                    </th>
                    <th width="180px">
                        <?php echo $this->gridHeaderCell('CompanyName','companyname', $filter, $page, $sort, $sortBy);?>
                    </th>
                    <th width="120px">
                        <?php echo $this->gridHeaderCell('Tag', 'tag', $filter, $page, $sort, $sortBy);?>
                    </th>
                    <th width="80px">
                        <?php echo $this->gridHeaderCell('Status','status', $filter, $page, $sort, $sortBy);?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $contact):?>
                    <tr>
                        <td>
                            <div class="checkbox" style="margin: 0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($contact->contactId);?>"/>
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cr_contact', array('action'=>'detail', 'id'=>$contact->contactId));?>" title="edit">
                                <?php echo $this->escapeHtml($contact->contactName);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->Phone);?>
                        </td>
                        <td>
                            <a href="mailto:<?php echo $this->escapeHtml($contact->Email);?>" title="edit">
                                <?php echo $this->escapeHtml($contact->Email);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->companyname);?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->Tag);?>
                        </td>
                        <td>
                            <?php
                            switch($contact->Status){
                                case'A':
                                    echo 'Active';
                                    break;
                                case'D':
                                    echo 'Inactive';
                                    break;
                                default:
                                    echo 'Invalid';
                                    break;
                            }
                            ?>
                        </td>

                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route'=>'cr_contact', 'sort'=>$sort, 'sortBy'=>$sortBy));?>
        </div>
    </div>
</div>

