<?php
/**
 *@var $this Zend\View\Renderer\PhpRenderer;
 **/
$title="Contacts";
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url:'<?php echo $this->url('cr_contact', array('action'=>'apiDelete'))?>',
                    data:$('input[name="chkId[]"]:checked'),
                    type:'POST',
                    success:function(data){
                        window.location.href="<?php echo $this->url('cr_contact')?>"
                    },
                    error: function(response){
                        var data = response.responseJSON;
                        alert(data.status.message);
                    }
                });
            }
        });
        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });

        $('input[name="chkId[]"]').change(function(){
            var total=$('input[name="chkId[]"]').length;
            var checks=$('input[name="chkId[]"]:checked').length;

            if(total==checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('contactFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("cr_contact", array('action'=>'detail', 'id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('cr_contact', array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                $columns = array(
                    array(
                        'type' => 'checkbox',
                        'value' => array('id' => 'chkAll'),
                        'attr' => array('class' => 'text-center', 'width' => '50px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Contact Name',
                            'col' => 'contactName',
                        ),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Phone',
                            'col' => 'phone',
                        ),
                        'attr' => array('width' => '200px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Email',
                            'col' => 'email',
                        ),
                        'attr' => array('width' => '200px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Company Name',
                            'col' => 'companyname',
                        ),
                        'attr' => array('width' => '180px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Tag',
                            'col' => 'tag',
                        ),
                        'attr' => array('width' => '120px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Status',
                            'col' => 'status',
                        ),
                        'attr' => array('width' => '80px'),
                    ),
                );

                echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php foreach($paginator as $contact):?>
                    <tr>
                        <td class="text-center">
                            <div class="checkbox" style="margin: 0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($contact->contactId);?>"/>
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cr_contact', array('action'=>'detail', 'id'=>$contact->contactId));?>" title="edit">
                                <?php echo $this->escapeHtml($contact->contactName);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->Phone);?>
                        </td>
                        <td>
                            <a href="mailto:<?php echo $this->escapeHtml($contact->Email);?>" title="edit">
                                <?php echo $this->escapeHtml($contact->Email);?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->companyname);?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contact->Tag);?>
                        </td>
                        <td>
                            <?php echo $this->constantConverter($contact->Status, 'default_status'); ?>
                        </td>

                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route'=>'cr_contact', 'sort'=>$sort, 'sortBy'=>$sortBy));?>
        </div>
    </div>
</div>

