<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/18/2015
 * Time: 12:48 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('SUNDEW MYANMAR'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/sundew.ico'))
        ->prependStylesheet($this->basePath() . '/css/sundew.css')
        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
        ->prependStylesheet($this->basePath() . '/fuelux/css/fuelux.css')
        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css');
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/fuelux/js/fuelux.js')
        ->prependFile($this->basePath() . '/js/moment.js')
        ->prependFile($this->basePath() . '/bootstrap/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js');
    ?>
</head>
<body class="fuelux">
<div class="container">
    <?php echo $this->content; ?>
</div>
<?php echo $this->inlineScript() ?>
</body>