<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/6/2015
 * Time: 10:15 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title = "Position";
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<hr />
<?php
$form->setAttribute('action', $this->url('hr_position', array('action' => 'detail', 'id' => $id)));
$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="col-md-8">
    <?php
    echo $this->formHidden($form->get('positionId'));
    echo $this->formHorizontal($form->get('name'));
    echo $this->formHorizontal($form->get('min_Salary'));
    echo $this->formHorizontal($form->get('max_Salary'));
    echo $this->formHorizontal($form->get('status'));
    ?>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" value="Save" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-save"></span>
                Save
            </button>
            <?php if($isEdit):?>
                <a onclick="return confirm('Are you sure to delete?')" href="<?php echo $this->url('hr_position', array('action'=>'delete', 'id'=>$id)); ?>" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash"></span>
                    Remove
                </a>
            <?php endif; ?>
            <a href="<?php echo $this->url('hr_position'); ?>" class="btn btn-default">
                <span class="glyphicon glyphicon-th-list"></span>
                Back to List
            </a>
        </div>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>
