<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/20/2015
 * Time: 11:09 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
$title = "Change password";
$this->headTitle($title);
?>
<h1><?php echo $title; ?></h1>
<hr />
<div class="col-sm-9">
    <?php if(!empty($message)) : ?>
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong><span class="glyphicon glyphicon-info-sign"></span></strong>
            <?php echo $message; ?>
        </div>
    <?php endif;?>
    <?php
    $form->setAttribute('action', $this->url('user', array('action' => 'password')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHorizontal($form->get('currentPassword'));
    echo $this->formHorizontal($form->get('password'));
    echo $this->formHorizontal($form->get('retypePassword'));
    ?>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" value="Save" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-save"></span>
                Save
            </button>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>
