<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 1/16/2015
 * Time: 3:55 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $filter Zend\InputFilter\InputFilter
 */
$title = 'Role Manager';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/treeview.css');
$this->headScript()->prependFile($this->basePath() . '/js/treeview.js');
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <?php echo $this->formTreeView($roles, $id); ?>
    </div>
    <div class="col-md-8">
        <?php
        echo $this->form()->openTag($form);
        echo $this->formHorizontal($form->get('roleId'));
        echo $this->formHorizontal($form->get('name'));
        echo $this->formHorizontal($form->get('description'));
        ?>
        <div class="form-group">
            <label class="control-label col-sm-3">Parent Role</label>
            <div class="col-sm-9" id="parentRole">
                <script type="text/javascript">
                    role_chose = function(value){
                        var currentId = parseInt($("input[name=roleId]").val());
                        if(value == currentId && currentId > 0){
                            alert("Parent can't same with current role.");
                            $("input[name=parentId]").val("");
                            return true;
                        }
                        $('input[name=parentId]').val(value);
                    }
                </script>
                <?= $this->formHidden($form->get('parentId')); ?>
                <?= $this->partial('shared/tree_chooser.phtml', array('data' => $roles,
                    'name' => 'rolePicker', 'callback' => 'role_chose',
                    'active' => $form->get('parentId')->getValue())) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3">Icon Class</label>
            <div class="col-sm-6">
                <?php echo $this->formInput($form->get('icon')); ?>
            </div>
            <div class="col-sm-3">
                <script type="text/javascript">
                    icon_chose = function(icon){
                        $("input[name=icon]").val(icon);
                    }
                </script>
                <?php echo $this->partial('shared/icon_chooser.phtml', array('callback' => 'icon_chose')); ?>
            </div>
        </div>
        <?php echo $this->formHorizontal($form->get('priority')); ?>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <a href="<?php echo $this->url("role"); ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-file"></span>
                    New
                </a>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    Save
                </button>
                <?php if($this->isEdit): ?>
                    <a href="<?= $this->url('role', array('action' => 'index', 'id' => $id)); ?>?action=clone"
                       class="btn btn-warning">
                        <span class="glyphicon glyphicon-copy"></span>
                        Clone
                    </a>
                    <a onclick="return confirm('Are you sure to delete?')" href="<?= $this->url('role', array('action' => 'index', 'id' => $id));?>?action=delete"
                        class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                        Remove
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

