<?php
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 1/16/2015
 * Time: 3:55 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $filter Zend\InputFilter\InputFilter
 */
$title = 'Account Type Manager';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath() . '/css/treeview.css');
$this->headScript()->prependFile($this->basePath() . '/js/treeview.js')
    ->prependFile($this->basePath() . '/js/bootstrap3-typeahead.js');
?>
<h2><?php echo $this->escapeHtml($title); ?></h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <?php echo $this->formTreeView($accountTypes, $id); ?>
    </div>
    <div class="col-md-8">
        <script type="text/javascript">
            $(function(){
                $.get('<?php echo $this->url('account_type', array('action' => 'jsonAll')); ?>', function(data){
                    $('#parentType #typeahead').typeahead({source: data, afterSelect:function(item){
                        var currentId = parseInt($("input[name=accountTypeId]").val());
                        if(item.accountTypeId == currentId && currentId > 0){
                            alert("Parent can't same with current menu.");
                            $("input[name=parentTypeId]").val("");
                            return;
                        }
                        $("input[name=parentTypeId]").val(item.accountTypeId);
                    }});
                });
            });
        </script>
        <?php
        echo $this->form()->openTag($form);
        echo $this->formHorizontal($form->get('accountTypeId'));
        echo $this->formHorizontal($form->get('code'));
        echo $this->formHorizontal($form->get('name'));
        echo $this->formHorizontal($form->get('baseType'));
        ?>
        <div class="form-group">
            <label class="control-label col-sm-3">Parent Type</label>
            <div class="col-sm-9" id="parentType">
                <script type="text/javascript">
                    parent_chose = function(value){
                        var currentId = parseInt($("input[name=accountTypeId]").val());
                        if(value == currentId && currentId > 0){
                            alert("Parent can't same with current type.");
                            $("input[name=parentTypeId]").val("");
                            return true;
                        }
                        $('input[name=parentTypeId]').val(value);
                    }
                </script>
                <?= $this->formHidden($form->get('parentTypeId')); ?>
                <?= $this->partial('shared/tree_chooser.phtml', array('data' => $accountTypes,
                    'name' => 'parentPicker', 'callback' => 'parent_chose',
                    'active' => $form->get('parentTypeId')->getValue())) ?>
            </div>
        </div>
        <?php echo $this->formHorizontal($form->get('status')); ?>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <a href="<?php echo $this->url("account_type"); ?>" class="btn btn-default">
                    <span class="glyphicon glyphicon-file"></span>
                    New
                </a>
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    Save
                </button>
                <?php if($this->isEdit): ?>
                    <a href="<?php echo $this->url("account_type", array('action' => 'index', 'id' => $id)); ?>?action=clone"
                        class="btn btn-warning">
                        <span class="glyphicon glyphicon-copy"></span>
                        Clone
                    </a>
                    <a onclick="return confirm('Are you sure to delete?')" class="btn btn-danger"
                       href="<?php echo $this->url("account_type", array('action' => 'index', 'id' => $id));?>?action=delete">
                        <span class="glyphicon glyphicon-trash"></span>
                        Remove
                    </a>
                <?php endif; ?>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>