<?php
/**
 * Created by PhpStrom.
 * User:NyanTun
 * Date:4/2/2015
 * Time:2:44 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
/**
 * Created by PhpStrom.
 * User:NyanTun
 * Date:4/2/2015
 * Time:2:44 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Vouchers";
$this->headTitle($title);
?>
<h1><?php echo $title;?></h1>

<script type="text/javascript">
    $(document).ready(function(){
        $("[data-toggle=popover]").popover();
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('voucherFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url('account_voucher',array('action'=>'export'));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th width="100px">
                            <?php echo $this->gridHeaderCell('Date','requestedDate');?>
                        </th>
                        <th width="150px">
                            <?php echo $this->gridHeaderCell('Voucher No','voucherNo');?>
                        </th>
                        <th width="200px">
                            <?php echo $this->gridHeaderCell('Requester','requester');?>
                        </th>
                        <th width="180px">
                            <?php echo $this->gridHeaderCell('Amount','amount');?>
                        </th>
                        <th>
                            <?php echo $this->gridHeaderCell('Description','description');?>
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($paginator as $voucher): ?>
                    <?php
                    $status = $this->constantConverter($voucher->status, 'account_status');
                    $class = '';
                    switch($voucher->status){
                        case 'A':
                            $class = 'info';
                            break;
                        case 'C':
                            $class = 'warning';
                            break;
                        case 'F':
                            $class = 'success';
                            break;
                    }?>
                    <tr class="<?php echo $class; ?>">
                        <td>
                            <?php echo substr($this->escapeHtml($voucher->requestedDate),0,10); ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('account_voucher', array('action' => 'detail', 'voucher' => $voucher->voucherNo)); ?>" title="edit">
                                <?php echo $this->escapeHtml($voucher->voucherNo); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->requester); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->amount) . ' ' . $this->escapeHtml($voucher->currency); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($voucher->description); ?>
                        </td>
                        <td>
                            <?php if($voucher->status == 'C') : ?>
                                <a data-original-title="Reason" href="#" class="btn btn-block btn-warning btn-xs" data-toggle="popover"
                                   title="Reason" data-content="<?php echo $voucher->reason; ?>" role="button" data-placement="bottom">
                                    Cancel
                                </a>
                            <?php else: ?>
                                <?php echo $this->escapeHtml($status); ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route' => 'account_voucher',
                'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>