<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/16/2015
 * Time: 11:12 AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 * @var $page Zend\Navigation\Page\Mvc
 */
?>
<ul class="nav navbar-nav">
    <?php foreach ($this->container as $page): ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if(!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if(!$hasChildren): ?>
            <li <?php if($page->isActive()) echo 'class="active"'?>>
                <?php echo $this->navigation()->menu()->htmlify($page, false); ?>
            </li>
        <?php else: ?>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <?php echo $this->translate($page->getLabel()) ?>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu multi-level" id="page_<?php echo $page->getId(); ?>">
                    <?php echo $this->partial('shared/sub_menu.phtml', array('pages' => $page->getPages())); ?>
                </ul>
            </li>
        <?php endif; ?>
    <?php endforeach ?>
</ul>