<?php
/**
 * Created by PhpStorm.
 * User:NyanTun
 * Date:5/11/2015
 * Time: 2:36 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Contract";
$this->headTitle($title);
?>
<h1><?php echo $title;?></h1>
<hr />
<?php
$form->setAttribute('action', $this->url('cr_contract', array('action' => 'detail', 'id' => $id)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('contractId'));
?>
<div class="row">
    <div class="col-md-8">
        <?php
        echo $this->formHorizontal($form->get('contractDate'));
        echo $this->formHorizontal($form->get('code'));
        echo $this->formHorizontal($form->get('companyId'));
        echo $this->formHorizontal($form->get('contactId'));
        ?>

        <div class="form-group">
            <label class="control-label col-sm-3">Amount</label>
            <div class="col-sm-5">
                <?php echo $this->formNumber($form->get('amount')); ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formSelect($form->get('currencyId')) ?>
            </div>
        </div>
        <?php
        echo $this->formHorizontal($form->get('contractFile'));
        echo $this->formHorizontal($form->get('notes'));
        echo $this->formHorizontal($form->get('status'));
        ?>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" value="Save" class="btn btn-primary">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    Save
                </button>
                <?php if($isEdit):?>
                    <a href="<?php echo $this->url('cr_contract', array('action'=>'detail', 'id'=>$id));?>?action=clone"
                        class="btn btn-warning">
                        <span class="glyphicon glyphicon-copy"></span>
                        Clone
                    </a>
                    <a onclick="return confirm('Are you sure to delete?')"
                       href="<?php echo $this->url('cr_contract', array('action'=>'delete', 'id'=>$id));?>" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                        Remove
                    </a>
                <?php endif; ?>
                <?php echo $this->backButton(); ?>
            </div>
        </div>
    </div>
</div>
<?= $this->form()->closeTag(); ?>
