<?php
/**
 * Created by PhpStorm.
 * User:NyanTun
 * Date:4/30/2015
 * Time:11:45
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Contract";
$this->headTitle($title);
$flashMesssages=$this->flashMessenger()->getMessages();
?>
<h1><?php echo $title;?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url : '<?php echo $this->url('cr_contract', array('action' => 'apiDelete')) ?>',
                    data : $('input[name="chkId[]"]:checked'),
                    type : 'POST',
                    success : function(data){
                        window.location.href = "<?php echo $this->url('cr_contract'); ?>"
                    },
                    error : function(response){
                        var data = response.responseJSON;
                        alert(data.status.message);
                    }
                });
            }
        });

        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });
        $('input[name="chkId[]"]').change(function(){
            var total = $('input[name="chkId[]"]').length;
            var checks = $('input[name="chkId[]"]:checked').length;
            if(total == checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('contractFilter'); ?>
            </div>
            <div class="col-md-offset-5 col-md-4 ">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("cr_contract",array('action'=>'detail','id'=>0));?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo$this->url('cr_contract',array('action'=>'export')); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                $columns = array(
                    array(
                        'type' => 'checkbox',
                        'value' => array('id' => 'chkAll'),
                        'attr' => array('class' => 'text-center', 'width' => '50px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Code',
                            'col' => 'code',
                        ),
                        'attr' => array('width' => '180px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Date',
                            'col' => 'contractDate',
                        ),
                        'attr' => array('width' => '150px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Amount',
                            'col' => 'amount',
                        ),
                        'attr' => array('width' => '150px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Status',
                            'col' => 'status',
                        ),
                        'attr' => array('width' => '120px'),
                    ),
                    array(
                        'type' => 'custom',
                        'value' => 'File',
                        'attr' => array('class' => 'text-center', 'width' => '80px'),
                    )
                );

                echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php foreach($paginator as $contract) : ?>
                    <tr>
                        <td class="text-center">
                            <div class="checkbox" style="margin: 0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($contract->contractId); ?>" />
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('cr_contract',array('action'=>'detail', 'id'=>$contract->contractId));?>" title="edit">
                                <?php echo $this->escapeHtml($contract->code); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contract->contractDate);?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($contract->amount) . ' ' . $contract->currencyCode;?>
                        </td>
                        <td>
                            <?php echo $this->constantConverter($contract->status, 'default_status'); ?>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo $this->url('cr_contract', array('action'=>'download', 'id'=>$contract->contractId));?>" class="btn btn-info btn-sm" title="Download">
                                <span class="glyphicon glyphicon-download"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>

    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route'=>'cr_contract', 'sort'=>$sort, 'sortBy'=>$sortBy));
            ?>
        </div>
    </div>
</div>



