<?php 
/**
 * Created by PhpStorm.
 * User: NyanTun
 * Date: 3/24/2015
 * Time: 5:08 PM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer 
 */
/**
 * Created by PhpStorm.
 * User:NyanTun
 * Date:3/26/2015
 * Time:2:04AM
 * Zend Code Completion
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$title="Routes";
$this->headTitle($title);
?>
<h1><?php echo $title;?></h1>
<script type="text/javascript">
    $(document).ready(function(){
        $("button#btnDelete").click(function(){
            if(confirm('Are you sure to delete selected records?')){
                $.ajax({
                    url : '<?php echo $this->url('route', array('action' => 'apiDelete')) ?>',
                    data : $('input[name="chkId[]"]:checked'),
                    type : 'POST',
                    success : function(data){
                        window.location.href = "<?php echo $this->url('route'); ?>";
                    },
                    error: function(response){
                        var data = response.responseJSON;
                        alert(data.status.message);
                    }
                });
            }
        });

        $("input#chkAll").change(function(){
            if($(this).checkbox('isChecked')){
                $('input[name="chkId[]"]').checkbox('check');
            }else{
                $('input[name="chkId[]"]').checkbox('uncheck');
            }
        });
        $('input[name="chkId[]"]').change(function(){
            var total = $('input[name="chkId[]"]').length;
            var checks = $('input[name="chkId[]"]:checked').length;
            if(total == checks){
                $("input#chkAll").checkbox('check');
            }else{
                $("input#chkAll").checkbox('uncheck');
            }
        });
    });
</script>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-3">
                <?php echo $this->gridFilter('routeFilter'); ?>
            </div>
            <div class="col-md-4 col-md-offset-5">
                <div class="text-right">
                    <div class="btn-group">
                        <a href="<?php echo $this->url("route", array('action' => 'detail', 'id' => 0)); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-file"></span>
                            New
                        </a>
                        <a href="<?php echo $this->url('route', array('action' => 'export')); ?>" class="btn btn-default">
                            <span class="glyphicon glyphicon-download"></span>
                            Export
                        </a>
                        <button type="button" id="btnDelete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="grid">
            <table class="table table-bordered table-striped table-hover">
                <?php
                $columns = array(
                    array(
                        'type' => 'checkbox',
                        'value' => array('id' => 'chkAll'),
                        'attr' => array('class' => 'text-center', 'width' => '50px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Route Name',
                            'col' => 'name',
                        ),
                        'attr' => array('width' => '220px'),
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Module',
                            'col' => 'module',
                        )
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Route',
                            'col' => 'route',
                        )
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Controller',
                            'col' => 'controller',
                        )
                    ),
                    array(
                        'type' => 'db',
                        'value' => array(
                            'title' => 'Is Api?',
                            'col' => 'isApi'
                        ),
                        'attr' => array('width' => '80px', 'class' => 'text-center'),
                    )
                );

                echo $this->gridHeader($columns);
                ?>
                <tbody>
                <?php foreach($paginator as $route) : ?>
                    <tr>
                        <td class="text-center">
                            <div class="checkbox" style="margin:0">
                                <label class="checkbox-custom" data-initialize="checkbox">
                                    <input type="checkbox" name="chkId[]" value="<?php echo $this->escapeHtml($route->routeId); ?>" />
                                </label>
                            </div>
                        </td>
                        <td>
                            <a href="<?php echo $this->url('route', array('action' => 'detail', 'id' => $route->routeId)); ?>" title="edit">
                                <?php echo $this->escapeHtml($route->name); ?>
                            </a>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($route->module); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($route->route); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($route->controller); ?>
                        </td>
                        <td class="text-center">
                            <?php echo $route->isApi ? 'Yes' : 'No'; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel-footer">
        <div class="text-center">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'shared/paginator.phtml', array('route' => 'route',
                'filter' => $filter, 'sort' => $sort, 'sortBy' => $sortBy)); ?>
        </div>
    </div>
</div>

